### ISSUE TITLE
UI updates - 001

### ISSUE THREAD

**Issue by vogelino** [vogelino/hidden-perspectives-app#18]
### Todos:
- [x] Update/add yellow color variables 
- [x] Add participant tooltips and hover colors
- [x] Update tags styles and add hover effects
- [x] Change fonts to Suisse
- [x] Add Symbols next to list view
- [x] Update tooltip styles and remove title (duplicated)
